# Generated by Django 4.1.3 on 2022-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('numero_conteiner', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('movimentacao', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
    ]
